### ISSUE TITLE
cant connect to remote pc

### ISSUE THREAD

**Issue by thnxcul8ter** [MCJack123/remote.craftos-pc.cc#2] opened 2021-11-17 21:52 UTC
whenever i try to press the connect to remote pc button i get this error
Could not connect to remote.craftos-pc.cc: certificate has expired
ive reinstalled the plugin ive reinstalled vscode 
i cant get it to work

**Comment by MCJack123** [comment] 2021-11-18 21:18
Duplicate of MCJack123/vscode-craftos-pc#7.

**Closed as completed by MCJack123** 2021-11-18 21:18 UTC
Labels: duplicate
